In [4]:
import numpy as np

In [5]:
n1=np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
n1

array([1, 2, 3, 4])

In [7]:
x=[]
len(dir(x))

47

In [8]:
len(dir(n1))

165

In [9]:
n1.shape # tells we have 4 values separated by commas.

(4,)

In [10]:
n2=np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


Creating matrix:-
- arange
- linspace
- random.rand
- random.randn
- random.randint
- eye
- ones
- zeros

In [11]:
x=np.arange(-10,10,.2)
x.shape

(100,)

In [12]:
y=np.linspace(1,5,10)
print(y)
y.shape

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


(10,)

In [13]:
np.random.rand(3,3) # Gives random values between 0 and 1.

array([[0.62080564, 0.46720389, 0.11419321],
       [0.7498326 , 0.66071852, 0.93177962],
       [0.38098744, 0.77419024, 0.88965095]])

In [14]:
np.random.randn(10)

array([ 0.25970672, -0.52598844, -0.01364803, -1.09025523, -0.54304043,
       -0.36826461, -0.26810091,  1.01544875, -0.93961973, -0.45804302])

In [15]:
np.random.randint(1,1000,(5,5)) # 5*5 matrix with random numbers between 1 and 1000.

array([[276, 266, 779, 972, 588],
       [531, 636, 902, 520, 767],
       [972, 110, 994, 925, 529],
       [481, 445,  89, 789, 470],
       [ 58, 489, 729, 119, 879]])

In [16]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(3,2))
print(x)
print(y)


[[9 7]
 [7 5]
 [3 3]]
[[6 3]
 [4 8]
 [7 1]]


In [17]:
x+5

array([[14, 12],
       [12, 10],
       [ 8,  8]])

In [18]:
x+y

array([[15, 10],
       [11, 13],
       [10,  4]])

In [19]:
x/y

array([[1.5       , 2.33333333],
       [1.75      , 0.625     ],
       [0.42857143, 3.        ]])

In [20]:
x*y

array([[54, 21],
       [28, 40],
       [21,  3]])

In [21]:
x.dot(y.T) # Transpose of y matrix.

array([[75, 92, 70],
       [57, 68, 54],
       [27, 36, 24]])

In [22]:
np.sin(x)

array([[ 0.41211849,  0.6569866 ],
       [ 0.6569866 , -0.95892427],
       [ 0.14112001,  0.14112001]])

In [23]:
print(x.sum())
print(x.mean())
print(x.std())
print(x.min())
print(x.max())
print(x.var())

34
5.666666666666667
2.211083193570267
3
9
4.888888888888889


In [25]:
a=np.linspace(0,5,50)
print(a.shape)
a2=a.reshape(10,5)
print(a2)
print(a2.shape)

(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.7755102  3.87755102 3.97959184]
 [4.08163265 4.18367347 4.28571429 4.3877551  4.48979592]
 [4.59183673 4.69387755 4.79591837 4.89795918 5.        ]]
(10, 5)


In [26]:
a2.reshape(5,5,2)  # 3D output.

array([[[0.        , 0.10204082],
        [0.20408163, 0.30612245],
        [0.40816327, 0.51020408],
        [0.6122449 , 0.71428571],
        [0.81632653, 0.91836735]],

       [[1.02040816, 1.12244898],
        [1.2244898 , 1.32653061],
        [1.42857143, 1.53061224],
        [1.63265306, 1.73469388],
        [1.83673469, 1.93877551]],

       [[2.04081633, 2.14285714],
        [2.24489796, 2.34693878],
        [2.44897959, 2.55102041],
        [2.65306122, 2.75510204],
        [2.85714286, 2.95918367]],

       [[3.06122449, 3.16326531],
        [3.26530612, 3.36734694],
        [3.46938776, 3.57142857],
        [3.67346939, 3.7755102 ],
        [3.87755102, 3.97959184]],

       [[4.08163265, 4.18367347],
        [4.28571429, 4.3877551 ],
        [4.48979592, 4.59183673],
        [4.69387755, 4.79591837],
        [4.89795918, 5.        ]]])

In [30]:
x=np.random.randint(1,10,(10,10))
print(x)

[[1 5 4 6 6 3 6 2 1 5]
 [1 3 3 1 2 9 6 5 4 7]
 [5 5 3 2 6 9 5 2 8 2]
 [4 7 3 3 2 7 8 6 3 7]
 [2 5 8 2 3 3 8 7 4 7]
 [4 2 6 2 9 8 8 5 5 7]
 [2 2 9 2 7 3 5 7 3 3]
 [1 1 4 1 4 5 6 9 9 6]
 [4 3 4 9 8 4 9 8 3 6]
 [9 1 3 6 7 9 7 8 9 8]]


In [33]:
print(x[0,0]) # first row first column
print(x[0,1]) # first row last column
print(x[-1,0]) # last row first column
print(x[-1,-1]) # last row last column

1
5
9
8


In [35]:
print(x[0]) # first row
print(x[1]) # second row
print(x[-1]) # last row
print(x[:3]) # first 3 rows
print(x[-3:]) # last 3 rows

[1 5 4 6 6 3 6 2 1 5]
[1 3 3 1 2 9 6 5 4 7]
[9 1 3 6 7 9 7 8 9 8]
[[1 5 4 6 6 3 6 2 1 5]
 [1 3 3 1 2 9 6 5 4 7]
 [5 5 3 2 6 9 5 2 8 2]]
[[1 1 4 1 4 5 6 9 9 6]
 [4 3 4 9 8 4 9 8 3 6]
 [9 1 3 6 7 9 7 8 9 8]]


In [37]:
print(x[:,0]) # first column
print(x[:,-1]) # last column
print(x[:,:3]) # first 3 column
print(x[:,-3:]) # last 3 column

[1 1 5 4 2 4 2 1 4 9]
[5 7 2 7 7 7 3 6 6 8]
[[1 5 4]
 [1 3 3]
 [5 5 3]
 [4 7 3]
 [2 5 8]
 [4 2 6]
 [2 2 9]
 [1 1 4]
 [4 3 4]
 [9 1 3]]
[[2 1 5]
 [5 4 7]
 [2 8 2]
 [6 3 7]
 [7 4 7]
 [5 5 7]
 [7 3 3]
 [9 9 6]
 [8 3 6]
 [8 9 8]]


In [38]:
print(x[:,[0,2,3,5]]) # will print 1st,3rd,4th and 6th column.

[[1 4 6 3]
 [1 3 1 9]
 [5 3 2 9]
 [4 3 3 7]
 [2 8 2 3]
 [4 6 2 8]
 [2 9 2 3]
 [1 4 1 5]
 [4 4 9 4]
 [9 3 6 9]]


Filtering:-

In [39]:
x<5  # boolean filter.

array([[ True, False,  True, False, False,  True, False,  True,  True,
        False],
       [ True,  True,  True,  True,  True, False, False, False,  True,
        False],
       [False, False,  True,  True, False, False, False,  True, False,
         True],
       [ True, False,  True,  True,  True, False, False, False,  True,
        False],
       [ True, False, False,  True,  True,  True, False, False,  True,
        False],
       [ True,  True, False,  True, False, False, False, False, False,
        False],
       [ True,  True, False,  True, False,  True, False, False,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True, False, False,  True, False, False,  True,
        False],
       [False,  True,  True, False, False, False, False, False, False,
        False]])

In [40]:
x[x<5]

array([1, 4, 3, 2, 1, 1, 3, 3, 1, 2, 4, 3, 2, 2, 2, 4, 3, 3, 2, 3, 2, 2,
       3, 3, 4, 4, 2, 2, 2, 2, 2, 3, 3, 3, 1, 1, 4, 1, 4, 4, 3, 4, 4, 3,
       1, 3])

In [41]:
x[x>5]

array([6, 6, 6, 9, 6, 7, 6, 9, 8, 7, 7, 8, 6, 7, 8, 8, 7, 7, 6, 9, 8, 8,
       7, 9, 7, 7, 6, 9, 9, 6, 9, 8, 9, 8, 6, 9, 6, 7, 9, 7, 8, 9, 8])

In [42]:
x[(x>=3) & (x<=6)]

array([5, 4, 6, 6, 3, 6, 5, 3, 3, 6, 5, 4, 5, 5, 3, 6, 5, 4, 3, 3, 6, 3,
       5, 3, 3, 4, 4, 6, 5, 5, 3, 5, 3, 3, 4, 4, 5, 6, 6, 4, 3, 4, 4, 3,
       6, 3, 6])

In [44]:
x[x>5].sum()

322