In [1]:
import numpy as np

In [2]:
n1=np.array([1,2,3,4])
print(n1)
print(type(n1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
n1

array([1, 2, 3, 4])

In [6]:
x=[]
len(dir(x))

47

In [7]:
len(dir(n1))

165

In [8]:
n1.shape # tells we have 4 values separated by commas.

(4,)

In [9]:
n2=np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


Creating matrix:-
- arange
- linspace
- random.rand
- random.randn
- random.randint
- eye
- ones
- zeros

In [12]:
x=np.arange(-10,10,.2)
x.shape

(100,)

In [15]:
y=np.linspace(1,5,10)
print(y)
y.shape

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


(10,)

In [17]:
np.random.rand(3,3) # Gives random values between 0 and 1.

array([[0.30098307, 0.24144093, 0.39802114],
       [0.80378431, 0.98163524, 0.80382067],
       [0.85985381, 0.01162197, 0.30114669]])

In [18]:
np.random.randn(10)

array([-0.38413454, -0.94806879,  0.30694539, -0.6734021 , -1.41425607,
        0.92973297,  1.26307069, -0.38415491, -1.17807591, -0.66865362])

In [19]:
np.random.randint(1,1000,(5,5)) # 5*5 matrix with random numbers between 1 and 1000.

array([[414, 417, 254, 768, 263],
       [355,  48, 474, 677, 266],
       [ 86, 361, 285,  74,  85],
       [267, 780, 693,   8, 771],
       [160, 444, 372, 796, 223]])

In [20]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(3,2))
print(x)
print(y)


[[3 2]
 [7 5]
 [1 8]]
[[4 9]
 [4 6]
 [8 8]]


In [21]:
x+5

array([[ 8,  7],
       [12, 10],
       [ 6, 13]])

In [22]:
x+y

array([[ 7, 11],
       [11, 11],
       [ 9, 16]])

In [23]:
x/y

array([[0.75      , 0.22222222],
       [1.75      , 0.83333333],
       [0.125     , 1.        ]])

In [24]:
x*y

array([[12, 18],
       [28, 30],
       [ 8, 64]])

In [26]:
x.dot(y.T) # Transpose of y matrix.

array([[30, 24, 40],
       [73, 58, 96],
       [76, 52, 72]])

In [27]:
np.sin(x)

array([[ 0.14112001,  0.90929743],
       [ 0.6569866 , -0.95892427],
       [ 0.84147098,  0.98935825]])

In [29]:
print(x.sum())
print(x.mean())
print(x.std())
print(x.min())
print(x.max())
print(x.var())

26
4.333333333333333
2.5603819159562025
1
8
6.5555555555555545
